"""Removed unique contraint from timestamp, made other columns optional

Revision ID: 34522ffd50ef
Revises: da0b1e3119cb
Create Date: 2024-10-13 23:48:42.103790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "34522ffd50ef"
down_revision: Union[str, None] = "da0b1e3119cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_observation",
        "volume",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "stock_observation",
        "trade_count",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "stock_observation",
        "vwap",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_index("ix_stock_observation_timestamp", table_name="stock_observation")
    op.create_index(
        op.f("ix_stock_observation_timestamp"),
        "stock_observation",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_observation_timestamp"), table_name="stock_observation"
    )
    op.create_index(
        "ix_stock_observation_timestamp",
        "stock_observation",
        ["timestamp"],
        unique=True,
    )
    op.alter_column(
        "stock_observation",
        "vwap",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "stock_observation",
        "trade_count",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "stock_observation",
        "volume",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
